### ISSUE TITLE
Cannot compile with Zephyr 3.7.99

### ISSUE THREAD

**Issue by StefanHri** [craigpeacock/Zephyr_WiFi#8]
`west build -b=esp32c6_devkitc` creates the following errors and warnings:
```sh
/home/stefan/workspaces/Zephyr_WiFi/src/wifi.c: In function 'handle_ipv4_result':
/home/stefan/workspaces/Zephyr_WiFi/src/wifi.c:64:46: error: 'struct net_if_addr_ipv4' has no member named 'addr_type'
   64 |         if (iface->config.ip.ipv4->unicast[i].addr_type != NET_ADDR_DHCP) {
      |                                              ^
/home/stefan/workspaces/Zephyr_WiFi/src/wifi.c:70:67: error: 'struct net_if_addr_ipv4' has no member named 'address'
   70 |                                 &iface->config.ip.ipv4->unicast[i].address.in_addr,
      |                                                                   ^
/home/stefan/workspaces/Zephyr_WiFi/src/wifi.c:74:55: error: 'struct net_if_ipv4' has no member named 'netmask'
   74 |                                 &iface->config.ip.ipv4->netmask,
      |                                                       ^~
[34/268] Building C object CMakeFiles/app.dir/src/ping.c.obj
/home/stefan/workspaces/Zephyr_WiFi/src/ping.c: In function 'icmp_echo_reply_handler':
/home/stefan/workspaces/Zephyr_WiFi/src/ping.c:33:1: warning: no return statement in function returning non-void [-Wreturn-type]
   33 | }
      | ^
/home/stefan/workspaces/Zephyr_WiFi/src/ping.c: In function 'ping':
/home/stefan/workspaces/Zephyr_WiFi/src/ping.c:57:72: warning: passing argument 3 of 'net_icmp_send_echo_request' from incompatible pointer type [-Wincompatible-pointer-types]
   57 |                 ret = net_icmp_send_echo_request(&icmp_context, iface, &dst_addr, NULL, &cycles);
      |                                                                        ^~~~~~~~~
      |                                                                        |
      |                                                                        struct sockaddr_in *
In file included from /home/stefan/workspaces/Zephyr_WiFi/src/ping.c:11:
/home/stefan/Programs/sources/zephyrproject/zephyr/include/zephyr/net/icmp.h:190:49: note: expected 'struct sockaddr *' but argument is of type 'struct sockaddr_in *'
  190 |                                struct sockaddr *dst,
      |                                ~~~~~~~~~~~~~~~~~^~~
/home/stefan/workspaces/Zephyr_WiFi/src/ping.c:47:37: warning: unused variable 'params' [-Wunused-variable]
   47 |         struct net_icmp_ping_params params;
      |                                     ^~~~~~
[47/268] Building C object zephyr/CMak...if/components/esp_mm/esp_mmu_map.c.obj
ninja: build stopped: subcommand failed.

```

**Comment by camiloVargasTechnaid** [comment]
Same problem in Zephyr 4.0.99
